Output dist/demo.gif
#Output dist/demo.mp4
#Output dist/demo.webm

Require ir

Set Theme "Catppuccin Frappe"
Set MarginFill "#6B50FF"
Set Margin 10
Set WindowBar Colorful
Set BorderRadius 10
Set Padding 30
Set Width 1200
Set Height 900
Set FontSize 26


Type "ir smashedr/bup"
Sleep 0.5s
Enter
Wait
Sleep 3s

Type "which bup"
Sleep 0.5s
Enter
Wait
Sleep 2s

Type "bup -V"
Sleep 0.5s
Enter
Wait
Sleep 2s

Type "ir list"
Sleep 0.5s
Enter
Wait
Sleep 3s

Type "clear"
Sleep 0.3s
Enter
