
Type "ir smashedr/bup"
Sleep 0.5s
Enter

Wait / bup_/
Sleep 1.5s
Up
Sleep 0.2s
Up
Sleep 0.5s
Down
Sleep 0.2s
Down
Sleep 0.5s
Enter
Wait /\> /
Sleep 1s
Backspace
Sleep 0.2s
Backspace
Sleep 0.2s
Type u
Sleep 0.2s
Type p
Sleep 0.5s
Enter
Sleep 2s

Type "which bup"
Sleep 0.5s
Enter
Wait
Sleep 1.5s

Type "bup -V"
Sleep 0.5s
Enter
Wait
Sleep 1.5s

Type "ir list"
Sleep 0.5s
Enter
Wait
Sleep 2s

Type "clear"
Sleep 0.3s
Enter
